name: py35
dependencies:
- openssl=1.0.2g=0
- pip=9.0.1=py35_0
- python=3.5.2=0
- readline=6.2=2
- setuptools=20.3=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - psycopg2>=2.6.1
